server.port=8080
spring.application.name=backend

# Uses env var MONGODB_URI if present; falls back to localhost
spring.data.mongodb.uri=mongodb+srv://enjirapunikhil_db_user:bhRzuoiYBsynk7JI@cluster0.5ndbdhn.mongodb.net/appdb?retryWrites=true&w=majority&appName=Cluster0

# Helpful logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
